---
title: "Gaze model analysis"
author: "Julia Prein"
date: "06/07/2023"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse) # data handling etc.
library(tidyboot) # for bootstrap CIs
library(coda) # HPDinterval
library(ggpubr) # stat_cor
library(ggdist) # stat_pointinterval
library(matrixStats) # logSumExp
library(ggridges) # for geom_density_ridges
library(ggthemes) # themes for plotting
library(cowplot) # ggdraw, draw_image, plot_grid
library(psych) #corr.test

options(scipen = 999)
theme_set(theme_classic())

# Seed for random number generation
set.seed(42)
```

```{r functions}
estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}

hdi_upper<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}

hdi_lower<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}
```

```{r load_data}
tango_kids <- readRDS("../data/tango-model-kids.rds")
tango_adults <- readRDS("../data/tango-model-adults.rds") %>% mutate(age_group = 18)
tango <- full_join(tango_kids, tango_adults)

# careful, this takes a while... 
model_kids <- readRDS("../data/gazemodel-kids.rds")
model_kids_dev_prior <- readRDS("../data/gazemodel-kids-dev-prior.rds")

model_adults_ind <- readRDS("../data/gazemodel-adults-ind.rds") %>% 
  rename("mode" = sdTol) %>% 
  mutate(
    age_group = 18, 
    age = 18,
    id = str_replace_all(id, "gafo_prolific_modelvalidation_vp", "gp1-")
  )

model_adults_bins <- readRDS("../data/gazemodel-adults-bins.rds") %>% 
  mutate(
    age_group = 18, 
    # transform into target width units
    data_mean = data_mean / 160, 
    model_mean = model_mean / 160,
  )
```

```{r sample}
gazemodel_sample_kids <- tango_kids %>% 
  group_by(age_group) %>%
  mutate(female = ifelse(gender == "f", 1, 0)) %>% 
  summarise(
    n_total = n_distinct(subj_id), 
    age_mean = mean(age, na.rm = T) %>% round(2),
    age_sd = sd(age, na.rm = T) %>% round(2),
    age_min = min(age, na.rm = T),
    age_max = max(age, na.rm = T),
    n_females = ceiling(sum(female/15)),
  )

gazemodel_sample_kids

gazemodel_sample_adults <- tango_adults %>% 
  mutate(female = ifelse(gender == "f", 1, 0)) %>% 
  summarise(
    n_total = n_distinct(subj_id), 
    age_mean = mean(age, na.rm = T) %>% round(2),
    age_sd = sd(age, na.rm = T) %>% round(2),
    age_min = min(age, na.rm = T),
    age_max = max(age, na.rm = T),
    n_females = ceiling(sum(female/15)),
  ) %>% 
  mutate(age_group = 18)

gazemodel_sample <- gazemodel_sample_kids %>% full_join(gazemodel_sample_adults)

write.csv(gazemodel_sample, "../saves/gazemodel_sample.csv", quote = F, row.names = F)
saveRDS(gazemodel_sample, "../saves/gazemodel_sample.rds")
```

```{r data_gazefunnel}
target_position_imprecision <- tango %>%
  group_by(age_group, target_position) %>%
  tidyboot_mean(column = click_dist_balloons, na.rm = TRUE)

target_position_imprecision_ind <- tango %>%
  group_by(subj_id, age_group, target_position) %>%
  summarize(mean = mean(click_dist_balloons, na.rm = TRUE))

gazefunnel <- ggplot() +
  geom_point(data = target_position_imprecision_ind, aes(x = target_position, y = mean, col = as.factor(age_group)), alpha = .1, position = position_dodge(width = 0.3)) +

  geom_pointrange(data = target_position_imprecision, aes(x = target_position, y = mean, ymin = ci_lower, ymax = ci_upper, col = as.factor(age_group)), pch = 18,  size = 1, position = position_dodge(width = .3)) +

  scale_y_continuous(limits = c(0, 7), breaks = seq(0, 7, 1)) +
  scale_color_manual(values = c("#c6d325", "#00b1ea", "#29485d", "darkgrey"), breaks = c("3", "4", "5", "18"), labels = c("3-year-olds", "4-year-olds", "5-year-olds", "Adults")) +
    labs(x = "Target position (binned)", y = "Average imprecision in target widths", col = "Age in years")

gazefunnel

# saveRDS(gazefunnel, "../saves/gazemodel_funnel.rds")
# ggsave("../figures/gazemodel_funnel.png", width = 6, height = 4, scale = 1.2)
```

# Inference 

```{r plot3A}
# developmental trajectory model inference parameter
inf_map_devp <- model_kids_dev_prior %>%
  filter(scope == "global", 
         parameter == "inference", 
         type != "sigma") %>%
  group_by(type) %>%
  summarise(mode = estimate_mode(value)) %>%
  pivot_wider(names_from = "type", values_from = "mode") %>%
  expand_grid(age = seq(0, 3, 0.1)) %>%
  mutate(sd = exp(intercept + slope * age))

inf_samp_devp <- model_kids_dev_prior %>%
  filter(scope == "global", 
         parameter == "inference", 
         type != "sigma") %>%
  pivot_wider(names_from = "type", values_from = "value") %>%
  sample_n(1000) %>%
  expand_grid(age = seq(0, 3, 0.1)) %>%
  mutate(sd = exp(intercept + slope * age))


id_devp <- model_kids_dev_prior %>%
  filter(scope == "id", 
         type == "sd") %>%
  group_by(id) %>%
  summarise(mode = estimate_mode(value),
            lci = hdi_lower(value), 
            uci = hdi_upper(value)) %>%
  left_join(tango_kids %>% 
              select(subj_id, age, age_group) %>% 
              rename(id = subj_id) %>% 
              distinct(id, .keep_all = T)) %>%
  ungroup()

model_adults_sd <- model_adults_ind %>% 
  summarize(
    mean_mode = mean(mode), 
    lci = hdi_lower(mode), 
    uci = hdi_upper(mode)
  )

dev_plot <- ggplot() +
  
  # children
  geom_point(data = id_devp, aes(x = age, y = mode), alpha = 0.75, color = "darkgrey") +
  geom_line(data = inf_samp_devp, aes(x = age + 3, y = sd, group = paste(chain,iteration)), col = "blue", alpha = .01) +
  geom_line(data = inf_map_devp, aes(x = age + 3, y = sd), col = "black", linewidth = 1.25) +
  
  # adults 
  geom_jitter(data = model_adults_ind, aes(x = 6.5, y = mode), alpha = 0.5, color = "darkgrey",  width = .1) + 
  geom_pointrange(data = model_adults_sd %>% head(1), aes(x = 6.5, y = mean_mode, ymin = lci, ymax = uci), size = 0.5) + 
  
  scale_x_continuous(limits = c(3, 6.7), breaks = seq(3, 6.5, 0.5), labels = c("3.0", "3.5", "4.0", "4.5", "5.0", "5.5", "6.0", "Adults")) + 
  scale_y_continuous(limits = c(0, 6), breaks = seq(0, 6, 0.25)) +
  coord_cartesian(ylim = c(0, 3)) +
  labs(x = "Age in years", y = expression(paste("Mode model parameter (", italic("\U03C3"[v]), ")")))

saveRDS(dev_plot, file = "../saves/gazemodel_dev_plot.rds")
dev_plot <- readRDS("../saves/gazemodel_dev_plot.rds")

# ggsave("../figures/gazemodel_dev.png", width = 8, height = 5, scale = 1, bg = "white")
# ggsave("../figures/gazemodel_dev.pdf", width = 8, height = 5, scale = 1, bg = "white")
```

## Correlation model vs data individual level / age

```{r plot3B}
comparison_model_data_devp <- model_kids_dev_prior %>%
  filter(scope == "id", type == "sd") %>%
  group_by(id) %>%
  summarise(model_mode = estimate_mode(value)) %>%
  left_join(
    tango_kids %>% 
      group_by(subj_id, age, age_group) %>%
      summarise(data_mean = mean(click_dist_balloons)) %>%
      rename(id = subj_id)
  )

comparison_model_data_adults <- tango_adults %>% 
  group_by(subj_id) %>% 
  summarize(
    data_mean = mean(click_dist_balloons)
  ) %>% 
  left_join(model_adults_ind %>% select(-lci, -uci) %>% rename("model_mode" = mode, "subj_id" = id))

comparison_model_data <- full_join(comparison_model_data_devp, comparison_model_data_adults) %>% 
  mutate(sample = ifelse(age < 18, "children", "adults"))

model_vs_data_plot <- ggplot(comparison_model_data, aes(x = model_mode, y = data_mean, group = sample)) +
  geom_point(aes(col = age)) +
  stat_cor(data = comparison_model_data %>% filter(sample == "children"), aes(label = paste(..r.label..)), method = "pearson", size = 4, r.accuracy = 0.01, cor.coef.name = "r", label.x = 0, label.y = 4.5) +
  
  stat_cor(data = comparison_model_data %>% filter(sample == "adults"), aes(label = paste(..r.label..)), method = "pearson", size = 4, r.accuracy = 0.01, cor.coef.name = "r", label.x = 0, label.y = 2.25) +
  
  geom_smooth(method = "lm", col = "darkgrey", alpha = 0.25) +
  
  labs(x = expression(paste("Mode model parameter (", italic("\U03C3"[v]), ")")), y = "Mean data imprecision", color = "Age") + 
  
  scale_x_continuous(limits = c(0, NA), n.breaks = 7) +
  scale_y_continuous(limits = c(0, NA), n.breaks = 5) +
  scale_color_viridis_c(direction = -1, alpha = 0.9, limits = c(3, 6), breaks = seq(3, 6, 0.5)) +
  theme_few() +
  theme(
    legend.position = c(0.37, 0.3),
    strip.text = element_text(face = "bold", size = 10), 
    legend.title = element_text(size = 8),
    legend.text = element_text(size = 8), 
    legend.box.background = element_rect(), 
    legend.key.height = unit(0.5, "cm"),
  ) +
  facet_wrap(~ factor(sample, levels = c("children", "adults"), labels = c("Child sample", "Adult sample")), scales = "free")

model_vs_data_plot

saveRDS(model_vs_data_plot, file = "../saves/gazemodel_model_vs_data.rds")
model_vs_data_plot <- readRDS("../saves/gazemodel_model_vs_data.rds")
# ggsave("../figures/gazemodel_model_vs_data.png", width = 8, height = 5, scale = 1, bg = "white")
# ggsave("../figures/gazemodel_model_vs_data.pdf", width = 8, height = 5, scale = 1, bg = "white")
```

# Inference parameters individuals

```{r id_inf}
# prepare data
id_inf <- model_kids_dev_prior %>%
  filter(scope == "id", parameter == "inference") %>% 
  group_by(id) %>% 
  mutate(mean = mean(value, na.rm = T))

idinf_plot <- id_inf %>% 
  slice_sample(n = 2000) %>% # for faster debugging
  full_join((tango_kids %>% select(subj_id, age, age_group)), by = join_by(id == subj_id)) %>% 
  ggplot(aes(x = value, y = reorder(id, mean), fill = age)) +
  geom_density_ridges(bandwidth = .05, rel_min_height = .01, size = .25, scale = 3, alpha = .5) + 
  scale_fill_viridis_c(direction = -1, alpha = 0.9, limits = c(3, 6), breaks = seq(3, 6, 0.5)) +
  scale_x_continuous(breaks = seq(0, 7, 0.5)) +
  coord_cartesian(xlim = c(0, 7)) +
  theme(axis.ticks.y = element_blank(), axis.text.y = element_blank()) + 
  labs(x = "Inference parameter", y = "Participants (ordered by mean)", fill = "Age")

idinf_plot
saveRDS(idinf_plot, "../saves/supplements_gazemodel_idinf_plot.rds")

ggsave("../figures/supplements_gazemodel_indinference.png", width = 5, height = 5)
ggsave("../figures/supplements_gazemodel_indinference.pdf", width = 5, height = 5)
```

```{r faceted_inf, message=FALSE, warning=FALSE}
faceted_inf <- model_kids_dev_prior %>%
  filter(scope == "id", parameter == "inference") %>%
  mutate(id = vctrs::vec_group_id(id)) %>% 
  ggplot() + 
  geom_density(aes(x = value, fill = factor(chain)), alpha = .5) +
  stat_pointinterval(aes(x = value)) +
  facet_wrap(~ id, nrow = 6, scales = "free") +
  scale_fill_viridis_d() +
  scale_x_continuous(limits = c(0, 3)) + 
  scale_y_continuous(limits = function(x){c(0, max(0.1, x))}) +
  labs(x = "Inference parameter value", y = "", fill = "Model chains") +
  theme_minimal()

faceted_inf
saveRDS(faceted_inf, "../saves/supplements_gazemodel_facetedinference.rds")
faceted_inf <- readRDS("../saves/supplements_gazemodel_facetedinference.rds")

ggsave("../figures/supplements_gazemodel_facetedinference.png", width = 10, height = 6, scale = 1.4, bg = "white")
ggsave("../figures/supplements_gazemodel_facetedinference.pdf", width = 10, height = 6, scale = 1.4, bg = "white")
```

# Recover U pattern

```{r get_click_prior}
get_click_prior <- function(sdTol, eyeCenterLY, eyeCenterLX, eyeCenterRY, eyeCenterRX, targetCenterY, targetCenterX, pupilLX, pupilRX, priorInt, priorSlope, age){

  if(eyeCenterLX > pupilLX) {
    tAlphaL = atan(abs(eyeCenterLX-targetCenterX)/(eyeCenterLY-targetCenterY))
  } else {
    tAlphaL = -atan(abs(eyeCenterLX-targetCenterX)/(eyeCenterLY-targetCenterY))
  }
  
  #noisyAlphaL = rnorm(1,tAlphaL, sdPer)
  
  if(eyeCenterRX > pupilRX) {
    tAlphaR = atan(abs(eyeCenterRX-targetCenterX)/(eyeCenterRY-targetCenterY))
  } else {
    tAlphaR = -atan(abs(eyeCenterRX-targetCenterX)/(eyeCenterRY-targetCenterY))
  }
  
  #noisyAlphaR = rnorm(1,tAlphaR, sdPer) 

  bRDist = c()
  
  bLDist = c()
  
  for (x in 1:1920){
    
  if(eyeCenterLX > x) {
    betaL = atan(abs(eyeCenterLX-x)/(eyeCenterLY-targetCenterY))
  } else {
    betaL = -atan(abs(eyeCenterLX-x)/(eyeCenterLY-targetCenterY))
  }
    betaLDist = dnorm(betaL,tAlphaL,sdTol, log = T)
    
  if(eyeCenterRX > x) {
    betaR = atan(abs(eyeCenterRX-x)/(eyeCenterRY-targetCenterY))
  } else {
    betaR = -atan(abs(eyeCenterRX-x)/(eyeCenterRY-targetCenterY))
  }
    betaRDist = dnorm(betaR,tAlphaR,sdTol, log = T)
    
    #betaDist = betaLDist + betaRDist
    
    #bDist[x] <- exp(betaDist)
    bRDist[x] <- betaRDist
    
    bLDist[x] <- betaLDist
    
  }
  
  xRDist = exp(bRDist-logSumExp(bRDist))
  
  xLDist = exp(bLDist-logSumExp(bLDist))
  
  priorSD = priorInt + priorSlope * age
  
  xDist = (xRDist * xLDist) * dnorm(seq(1:1920), mean = 960, sd = priorSD)
  
  dist = xDist / sum(xDist)
  
  click = sample(1:1920, prob = xDist, size = 1)-1
  
  return(click)
}
```

```{r plot3C}
# u pattern recovery
ind_sd <- model_kids_dev_prior %>%
  filter(scope == "id", type == "sd") %>%
  group_by(id) %>%
  summarise(sdTol = estimate_mode(value)) %>%
  left_join(tango_kids %>% rename(id = subj_id,
                          eyeCenterLY = eye_center_left_y,
                          eyeCenterLX = eye_center_left_x,
                          eyeCenterRY = eye_center_right_y,
                          eyeCenterRX = eye_center_right_x,
                          pupilLX = pupil_final_left_x,
                          pupilRX = pupil_final_right_x,
                          targetCenterX = target_center_x,
                          targetCenterY = target_center_y) %>%
              mutate(clickDist = abs(click_dist_from_target_center_x)) %>%
              select(id, age, age_group, trial_nr, eyeCenterLX, eyeCenterLY, eyeCenterRX, eyeCenterRY, pupilLX, pupilRX, targetCenterY, targetCenterX, clickDist))

ind_sd_long <- ind_sd %>% slice(rep(1:n(), each = 100))

saveRDS(ind_sd_long, file = "../saves/gazemodel_ind_sd_long.rds")
# ind_sd_long <- readRDS("../saves/gazemodel_ind_sd_long.rds")

priorMode <- model_kids_dev_prior %>%
  filter(scope == "global",
         parameter == "priorSd",
         type != "sigma") %>%
  group_by(type) %>%
  summarise(
    mode = estimate_mode(value), 
    lci = hdi_lower(value), 
    uci = hdi_upper(value))

saveRDS(priorMode, file = "../saves/gazemodel_prior.rds")
# priorMode <- readRDS("../saves/gazemodel_prior.rds")

# # careful, this runs a while... (ca. 30-45 min for me)

gen_model_clicks <- ind_sd_long %>%
  rowwise() %>%
  mutate(modelClick = get_click_prior(
          sdTol = sdTol,
          eyeCenterLY = eyeCenterLY,
          eyeCenterLX = eyeCenterLX,
          eyeCenterRY = eyeCenterRY,
          eyeCenterRX = eyeCenterRX,
          targetCenterX = targetCenterX,
          pupilLX = pupilLX,
          pupilRX = pupilRX,
          targetCenterY = targetCenterY,
          priorInt = priorMode %>% filter(type == "intercept") %>% pull(mode),
          priorSlope = priorMode %>% filter(type == "slope") %>% pull(mode),
          age = age
          ))

saveRDS(gen_model_clicks, file = "../saves/gazemodel_gen_model_clicks.rds")
# gen_model_clicks <- readRDS("../saves/gazemodel_gen_model_clicks.rds")

modelpred_gaze <- gen_model_clicks %>%
  mutate(
    modelClickDist = abs(modelClick - targetCenterX),
    targetBin = cut(targetCenterX,
                    breaks = seq(from = 0, to = 1920, by = 192),
                    labels = as.character(1:10))
  ) %>%
  group_by(age_group, targetBin) %>%
  summarise(
    data_mean = mean(clickDist) / 160,
    model_mean = mean(modelClickDist) / 160,
  )

saveRDS(modelpred_gaze, "../saves/gazemodel_modelpred_gaze.rds")
modelpred_gaze <- readRDS("../saves/gazemodel_modelpred_gaze.rds")
    
u_data <- full_join(modelpred_gaze, model_adults_bins)
saveRDS(u_data, "../saves/gazemodel_u_data.rds")
# u_data <- readRDS("../saves/gazemodel_u_data.rds")

u_plot <- u_data %>%
  pivot_longer(cols = c(data_mean, model_mean), names_to = "source", values_to = "imprecision") %>%
  mutate(
    age_group = factor(age_group, levels = c(3, 4, 5, 18), labels = c("3-year-olds", "4-year-olds", "5-year-olds", "Adults")), 
  ) %>% 
  ggplot(aes(x = targetBin, y = imprecision, col = source)) +
  geom_point(alpha = 0.8) +
  facet_grid(~ age_group) +
  scale_y_continuous(limits = c(0, 5.5), breaks = seq(0, 5.5, 0.5)) +
  scale_color_manual(values = c("darkgrey", "darkblue"), labels = c("Data", "Model prediction")) +
  labs(x = "Target bin", y = "Imprecision", color = "Source") + 
  theme_few() +
  theme(
    legend.position = c(0.881, 0.7), # c(0,0) bottom left, c(1,1) top-right
    strip.text = element_text(face = "bold", size = 10), 
    legend.title = element_text(size = 8),
    legend.text = element_text(size = 8), 
    legend.box.background = element_rect(), 
    legend.key.height = unit(0.4, "cm"),
    legend.key.width = unit(-1.2, "cm"),
    plot.margin = margin(0.2, 0, 0.1, 0.2, "cm") # t r b l
  )

u_plot
saveRDS(u_plot, "../saves/gazemodel_u_plot.rds")
u_plot <- readRDS("../saves/gazemodel_u_plot.rds")

# ggsave("../figures/gazemodel_Uplot.png", width = 8, height = 5, scale = 1, bg = "white")
# ggsave("../figures/gazemodel_Uplot.pdf", width = 8, height = 5, scale = 1, bg = "white")
```

```{r modelpred_gaze_plot}
# correlation model predicted imprecision vs data imprecision across target positions
modelpred_gaze_plot <- modelpred_gaze %>% 
  ggplot(., aes(x = model_mean, y = data_mean)) +
  geom_point(aes(col = targetBin, shape = as.factor(age_group))) +
  stat_cor(method = "pearson", label.x = 0.2, label.y = 4.9, aes(label = paste(..r.label..)), size = 4, r.accuracy = 0.01, cor.coef.name = "r") +
  geom_abline(intercept = 0, slope = 1, linetype = 3) +
  scale_color_brewer(palette="BrBG") +
  labs(x = "Mean predicted imprecision", y = "Mean data imprecision", color = "Target bin", shape = "Age group") + 
  scale_x_continuous(limits = c(0, 5.5), breaks = seq(0, 5, 1)) + 
  scale_y_continuous(limits = c(0, 5.5), breaks = seq(0, 5, 1)) 

modelpred_gaze_plot
saveRDS(modelpred_gaze_plot, "../saves/gazemodel_modelpred_gaze_plot.rds")
# ggsave("../figures/gazemodel_modelpred_gaze_plot.png", width = 8, height = 5, scale = 1, bg = "white")
# ggsave("../figures/gazemodel_modelpred_gaze_plot.pdf", width = 8, height = 5, scale = 1, bg = "white")
```

# Alternative models click generation

## Center bias model

```{r get_click_center}
get_click_center <- function(){

  xDist = dnorm(seq(1:1920), mean = 960, sd = 160)
  
  click = sample(1:1920, prob = xDist, size = 1)-1
  
  return(click)
}
```

```{r center_model}
gen_model_clicks_center <- ind_sd_long %>%
  rowwise()%>%
  mutate(modelClick = get_click_center())

modelpred_center <- gen_model_clicks_center %>%
  mutate(
    modelClickDist = abs(modelClick - targetCenterX),
    targetBin = cut(targetCenterX, 
                    breaks = seq(from = 0, to = 1920, by = 192),
                    labels = as.character(1:10))) %>%
  group_by(age_group, targetBin) %>%
  summarise(
    data_mean = mean(clickDist) / 160, 
    model_mean = mean(modelClickDist) / 160, 
  )

saveRDS(modelpred_center, file = "../saves/gazemodel_modelpred_center.rds")
modelpred_center <- readRDS(file = "../saves/gazemodel_modelpred_center.rds")

# facetted U plot
modelpred_center %>%
  pivot_longer(cols = c(data_mean, model_mean), names_to = "source", values_to = "imprecision") %>%
  mutate(
    age_group = factor(age_group, levels = c(3, 4, 5), labels = c("3-year-olds", "4-year-olds", "5-year-olds")), 
  ) %>% 
  ggplot(aes(x = targetBin, y = imprecision, col = source)) +
  geom_point(alpha = 0.8) +
  facet_grid(~ age_group) +
  scale_y_continuous(limits = c(0, 5.5), breaks = seq(0, 5.5, 0.5)) +
  scale_color_manual(values = c("darkgrey", "darkblue"), labels = c("Data", "Model prediction")) +
  labs(x = "Target bin", y = "Imprecision", color = "Source") + 
  theme_few() +
  theme(
    legend.position = c(0.84 , 0.8), # c(0,0) bottom left, c(1,1) top-right
    legend.background = element_rect(color = "darkgrey", size = 0.1), 
    legend.text = element_text(size = 8),
    strip.text = element_text(face = "bold", size = 12)
  )

# corr plot
modelpred_center_plot <- modelpred_center %>% 
  ggplot(., aes(x = model_mean, y = data_mean)) +
  geom_point(aes(col = targetBin, shape = as.factor(age_group)), size = 0.8) +
  stat_cor(method = "pearson", label.x = 0.2, label.y = 4.9, aes(label = paste(..r.label..)), size = 3, r.accuracy = 0.01, cor.coef.name = "r") +
  geom_abline(intercept = 0, slope = 1, linetype = 3) +
  scale_color_brewer(palette="BrBG") +
  labs(x = "Mean predicted imprecision", y = "Mean data imprecision", color = "Target bin", shape = "Age group") + 
  scale_x_continuous(limits = c(0, 5.5), breaks = seq(0, 5, 1)) + 
  scale_y_continuous(limits = c(0, 5.5), breaks = seq(0, 5, 1)) 

modelpred_center_plot
saveRDS(modelpred_center_plot, "../saves/gazemodel_modelpred_center_plot.rds")
# ggsave("../figures/gazemodel_modelpred_center_plot.png", width = 10, height = 5, scale = 1.4, bg = "white")
# ggsave("../figures/gazemodel_modelpred_center_plot.pdf", width = 10, height = 5, scale = 1.4, bg = "white")
```

## Random clicks model 

```{r get_click_random}
get_click_random <- function(){

  xDist = dunif(seq(1:1920), min = 1, max = 1920)
  
  click = sample(1:1920, prob = xDist, size = 1)-1
  
  return(click)
}
```

```{r random_model}
gen_model_clicks_random <- ind_sd_long %>%
  rowwise() %>%
  mutate(modelClick = get_click_random())

modelpred_random <- gen_model_clicks_random %>%
  mutate(
    modelClickDist = abs(modelClick - targetCenterX),
    targetBin = cut(targetCenterX, 
                    breaks = seq(from = 0, to = 1920, by = 192),
                    labels=as.character(1:10))
  ) %>%
  group_by(age_group, targetBin) %>%
  summarise(
    data_mean = mean(clickDist) / 160, 
    model_mean = mean(modelClickDist) / 160
  )

saveRDS(modelpred_random, file = "../saves/gazemodel_modelpred_random.rds")
modelpred_random <- readRDS(file = "../saves/gazemodel_modelpred_random.rds")

# facetted U plot
modelpred_random %>%
  pivot_longer(cols = c(data_mean, model_mean), names_to = "source", values_to = "imprecision") %>%
  mutate(
    age_group = factor(age_group, levels = c(3, 4, 5), labels = c("3-year-olds", "4-year-olds", "5-year-olds")), 
  ) %>% 
  ggplot(aes(x = targetBin, y = imprecision, col = source)) +
  geom_point(alpha = 0.8) +
  facet_grid(~ age_group) +
  scale_y_continuous(limits = c(0, 5.5), breaks = seq(0, 5.5, 0.5)) +
  scale_color_manual(values = c("darkgrey", "darkblue"), labels = c("Data", "Model prediction")) +
  labs(x = "Target bin", y = "Imprecision", color = "Source") + 
  theme_few() +
  theme(
    legend.position = c(0.84 , 0.8), # c(0,0) bottom left, c(1,1) top-right
    legend.background = element_rect(color = "darkgrey", size = 0.1), 
    legend.text = element_text(size = 8),
    strip.text = element_text(face = "bold", size = 12)
  )

# corr plot
modelpred_random_plot <- modelpred_random %>% 
  ggplot(., aes(x = model_mean, y = data_mean)) +
  geom_point(aes(col = targetBin, shape = as.factor(age_group)), size = 0.8) +
  stat_cor(method = "pearson", label.x = 0.2, label.y = 4.9, aes(label = paste(..r.label..)), size = 3, r.accuracy = 0.01, cor.coef.name = "r") +
  geom_abline(intercept = 0, slope = 1, linetype = 3) +
  scale_color_brewer(palette="BrBG") +
  labs(x = "Mean predicted imprecision", y = "Mean data imprecision", color = "Target bin", shape = "Age group") + 
  scale_x_continuous(limits = c(0, 5.5), breaks = seq(0, 5, 1)) + 
  scale_y_continuous(limits = c(0, 5.5), breaks = seq(0, 5, 1)) 

modelpred_random_plot
saveRDS(modelpred_random_plot, "../saves/gazemodel_modelpred_random_plot.rds")
# ggsave("../figures/gazemodel_modelpred_random_plot.png", width = 10, height = 5, scale = 1.4, bg = "white")
# ggsave("../figures/gazemodel_modelpred_random_plot.pdf", width = 10, height = 5, scale = 1.4, bg = "white")
```

## Combine plots of predictions from 3 models

```{r plot3D}
modelpred_gaze_plot <- readRDS("../saves/gazemodel_modelpred_gaze_plot.rds")
modelpred_center_plot <- readRDS("../saves/gazemodel_modelpred_center_plot.rds")
modelpred_random_plot <- readRDS("../saves/gazemodel_modelpred_random_plot.rds")

corr_model_pred_plot <- ggarrange(
  
  modelpred_gaze_plot + 
    theme(legend.position = c(0.85, 0.38), 
          legend.title = element_text(size = 6),
          legend.text = element_text(size = 6), 
          legend.box.background = element_rect(), 
          legend.key.height = unit(0.28, "cm"),
          legend.key.width = unit(-1.8, "cm"),
          plot.margin = margin(0.2, -2, 0.1, 0.2, "cm") # t r b l
         ),
  
  ggarrange(
    modelpred_center_plot + 
      labs(title = "Center bias model", x = "", y = "") +
      theme(legend.position = "none", 
            axis.text = element_text(size = 6), 
            plot.title = element_text(size = 8), 
            plot.subtitle = element_text(size = 8), 
            plot.margin = margin(0.2, 0.2, 0.2, 0, "cm")),
    
    modelpred_random_plot + 
      labs(title = "Random guessing model", x = "", y = "") +
      theme(legend.position = "none", 
            axis.text = element_text(size = 6), 
            plot.title = element_text(size = 8), 
            plot.subtitle = element_text(size = 8), 
            plot.margin = margin(0.2, 0.2, 0.2, 0, "cm")), 
    nrow = 2
  ), 
  
  ncol = 2, 
  widths = c(1.5, 1), 
  align = "v"
  )

corr_model_pred_plot
saveRDS(corr_model_pred_plot, file = "../saves/gazemodel_corr_model_pred_plot.rds")
```

```{r get_click_motornoise}
get_click_motornoise <- function(targetCenterX){
  xDist = dnorm(seq(1:1920), mean = targetCenterX, sd = 160)
  
  click = sample(1:1920, prob = xDist, size = 1)-1
  
  return(click)
}
```

```{r get_click_linetracing}
get_click_linetracing <- function(targetCenterX){
  return(targetCenterX)
}
```

# Plot 

```{r arrange_plot}
dev_plot <- readRDS(file = "../saves/gazemodel_dev_plot.rds")
model_vs_data_plot <- readRDS(file = "../saves/gazemodel_model_vs_data.rds")
u_plot <- readRDS("../saves/gazemodel_u_plot.rds")
corr_model_pred_plot <- readRDS("../saves/gazemodel_corr_model_pred_plot.rds")

gazemodel_plot <- ggarrange(
  dev_plot, 
  NULL, 
  model_vs_data_plot, 
  
  u_plot, 
  NULL, 
  corr_model_pred_plot, 
  
  ncol = 3, 
  nrow = 2, 
  widths = c(13, 1, 12), 
  labels = c("A", "", "B", "C", "", "D")
)

gazemodel_plot
saveRDS(gazemodel_plot, "../saves/gazemodel_plot.rds")
ggsave("../figures/gazemodel_plot.png", width = 8, height = 5, scale = 1.5, bg = "white")
ggsave("../figures/gazemodel_plot.pdf", width = 8, height = 5, scale = 1.4, bg = "white", device = cairo_pdf)
# add cairo_pdf to enable greek symbols in pdf saving
```


```{r results_table}
# create tibble for reading out stats results in rmd manuscript
corr_gazemodel_param_children <- comparison_model_data_devp %>% select(model_mode, data_mean) %>% corr.test(method = "pearson")

corr_gazemodel_param_adults <- comparison_model_data_adults %>% select(model_mode, data_mean) %>% corr.test(method = "pearson")

# this is children only 
corr_gazemodel_pred <- modelpred_gaze %>% ungroup() %>% select(model_mean, data_mean) %>% corr.test(method = "pearson")
corr_centermodel_pred <- modelpred_center %>% ungroup() %>% select(model_mean, data_mean) %>% corr.test(method = "pearson")
corr_randommodel_pred <- modelpred_random %>% ungroup() %>% select(model_mean, data_mean) %>% corr.test(method = "pearson")

corrs <- rbind(
  cbind(corr_gazemodel_param_children$ci, n = corr_gazemodel_param_children$n), 
  cbind(corr_gazemodel_param_adults$ci, n = corr_gazemodel_param_adults$n), 
  cbind(corr_gazemodel_pred$ci, n = corr_gazemodel_pred$n), 
  cbind(corr_centermodel_pred$ci, n = corr_centermodel_pred$n), 
  cbind(corr_randommodel_pred$ci, n = corr_randommodel_pred$n)
  ) %>% 
  rownames_to_column(var = "corr") %>% 
  mutate(
    corr = recode(
            corr,
            `mdl_m-dt_mn` = "gazemodel_param_kids", 
            `mdl_m-dt_mn1` = "gazemodel_param_adults", 
            `mdl_m-dt_mn2` = "gazemodel_pred_kids", 
            `mdl_m-dt_mn3` = "centermodel_pred_kids", 
            `mdl_m-dt_mn4` = "randommodel_pred_kids", 
           ), 
  ) %>% 
  mutate(across(2:4, ~round(.x, 2))) 

corrs
saveRDS(corrs, file = "../saves/gazemodel_correlations.rds")
```

# Model comparison BayesFactor

```{r read_data_mcomparison}
modelcomparison_kids_bf <- readRDS("../data/gazemodel-kids-comparison-bf.rds")
modelcomparison_kids_samples <- readRDS("../data/gazemodel-kids-comparison-samples.rds")
```

```{r mcomparison}
# same as reading in modelcomparison_kids_bf
modelcomparison_kids_samples %>%
  group_by(model) %>%
  summarise(margllh = logSumExp(like)) %>%
  pivot_wider(names_from = model, values_from = margllh) %>%
  summarise(bf_inf_center = inf - center, 
            bf_inf_guess = inf - guess)
```

# Headlight distribution for plots

```{r get_dist}
get_dist <- function(sdTol, eyeCenterLY, eyeCenterLX, eyeCenterRY, eyeCenterRX, targetCenterY, targetCenterX, pupilLX, pupilRX){

  if(eyeCenterLX > pupilLX) {
    tAlphaL = atan(abs(eyeCenterLX-targetCenterX)/(eyeCenterLY-targetCenterY))
  } else {
    tAlphaL = -atan(abs(eyeCenterLX-targetCenterX)/(eyeCenterLY-targetCenterY))
  }

  #noisyAlphaL = rnorm(1,tAlphaL, sdPer)

  if(eyeCenterRX > pupilRX) {
    tAlphaR = atan(abs(eyeCenterRX-targetCenterX)/(eyeCenterRY-targetCenterY))
  } else {
    tAlphaR = -atan(abs(eyeCenterRX-targetCenterX)/(eyeCenterRY-targetCenterY))
  }

  #noisyAlphaR = rnorm(1,tAlphaR, sdPer)

  bRDist = c()

  bLDist = c()

  for (x in 1:1920){

  if(eyeCenterLX > x) {
    betaL = atan(abs(eyeCenterLX-x)/(eyeCenterLY-targetCenterY))
  } else {
    betaL = -atan(abs(eyeCenterLX-x)/(eyeCenterLY-targetCenterY))
  }
    betaLDist = dnorm(betaL,tAlphaL,sdTol, log = T)

  if(eyeCenterRX > x) {
    betaR = atan(abs(eyeCenterRX-x)/(eyeCenterRY-targetCenterY))
  } else {
    betaR = -atan(abs(eyeCenterRX-x)/(eyeCenterRY-targetCenterY))
  }
    betaRDist = dnorm(betaR,tAlphaR,sdTol, log = T)

    #betaDist = betaLDist + betaRDist

    #bDist[x] <- exp(betaDist)
    bRDist[x] <- betaRDist

    bLDist[x] <- betaLDist

  }

  xRDist = exp(bRDist-logSumExp(bRDist))

  xLDist = exp(bLDist-logSumExp(bLDist))

  xDist = xRDist * xLDist

  dist = xDist / sum(xDist)

  # click = sample(1:1920, prob = xDist, size = 1)-1

  return(dist)
}
```

```{r headlight_dist}
headlight_df <- data.frame(
  coord = 1:1920,
  sdTol = "0.175"
)

for (i in c(960,1736)){

  probdist <-  get_dist(
    sdTol = 0.175,
    targetCenterX = i,
    eyeCenterLY = 937.8,
    eyeCenterLX = 872.12,
    eyeCenterRY = 937.8,
    eyeCenterRX = 1045.89,
    targetCenterY = 127.5,
    pupilLX = i-1,
    pupilRX = i-1)

    colname = as.character(i)

    headlight_df[, colname] <- probdist

  }

headlight_df %>%
  pivot_longer(names_to = "target_coordinate", values_to = "probability", cols = c(-coord, -sdTol)) %>%
  filter(target_coordinate == "1736") %>%
  ggplot(aes(x = coord, y = probability, group = interaction(target_coordinate,sdTol))) +
  geom_density(stat = "identity", color = "blue", fill = "blue", alpha = .5) +
  ylim(0, 0.006) +
  scale_x_continuous(limits = c(0, 1920), breaks = seq(0, 1920, 480)) +
  guides(fill = F) +
  # geom_vline(aes(xintercept = as.numeric(target_coordinate)), lty = 2, alpha = .25) +
  # labs(x = "Coordinate", y = "Probability") +
  # scale_fill_colorblind(name = "Inference SD") +
  theme_few() +
  theme(
    panel.background = element_rect(fill = "transparent",colour = NA), # or theme_blank()
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    plot.background = element_rect(fill = "transparent",colour = NA)
)

ggsave("../figures/gazemodel_headlight_dist_side.png", width = 15, height = 4, bg = "transparent")

##  Standard normal dist
dnorm_one_sd <- function(x){
  norm_one_sd <- dnorm(x)
  # Have NA values outside interval x in [-1, 1]:
  norm_one_sd[x <= -1 | x >= 1] <- NA
  return(norm_one_sd)
}

ggplot(data.frame(x = c(-4, 4)), aes(x = x)) +
  stat_function(fun = dnorm, color = "darkgrey", linewidth = 2) +
  stat_function(fun = dnorm_one_sd, geom = "area", fill = "blue", alpha = 0.5) +
  # geom_vline(aes(xintercept = 0), lty = 2, color = "blue") +
  theme_void()

ggsave("../figures/gazemodel_normal_dist.png", width = 10, height = 4)
```

# Simulated clicks from alternative models

```{r simulated_data}
simulated_data <- gen_model_clicks %>% 
  ungroup() %>%
  mutate(
    model_dist = modelClick - targetCenterX,
  ) %>%
  rename(target_center_x = targetCenterX) %>%
  group_by(id, trial_nr, target_center_x) %>% 
  summarize(
    gazemodel_click = mean(modelClick),
    gazemodel_dist = mean(model_dist),
  ) %>% 
  mutate(
    # line_click = target_center_x,
    linetracing_click = get_click_linetracing(target_center_x),
    linetracing_dist = linetracing_click - target_center_x, # = 0
    
    # motornoise_click = rnorm(n = n(), mean = target_center_x, sd = 160) %>% round(digits = 2),
    motornoise_click = get_click_motornoise(target_center_x),
    motornoise_dist = motornoise_click - target_center_x,

    # random_click = runif(n = n(), min = 0, max = 1920) %>% round(digits = 2), 
    random_click = get_click_random(),
    random_dist = random_click - target_center_x,

    # center_click = rnorm(n = n(), mean = 960, sd = 160) %>% round(digits = 2),
    center_click = get_click_center(),
    center_dist = center_click - target_center_x,
  )

simulated_data <- tango_kids %>% 
  select(subj_id, age, age_group, trial_nr, target_position, target_center_x, click_scaled_x, click_dist_from_target_center_x) %>% 
  rename(data_click = click_scaled_x, data_dist = click_dist_from_target_center_x) %>% 
  full_join(simulated_data, by = c("subj_id" = "id", "trial_nr", "target_center_x"))

simulated_wide <- simulated_data

simulated_mean <- simulated_data %>% 
    group_by(target_position) %>%
  summarise(
    data_click = mean(data_click), 
    gazemodel_click = mean(gazemodel_click),
    linetracing_click = mean(linetracing_click),
    motornoise_click = mean(motornoise_click),
    random_click = mean(random_click),
    center_click = mean(center_click),
    
    data_dist = mean(abs(data_dist)), 
    gazemodel_dist = mean(abs(gazemodel_dist)),
    motornoise_dist = mean(abs(motornoise_dist)),
    linetracing_dist = mean(abs(linetracing_dist)),
    random_dist = mean(abs(random_dist)),
    center_dist = mean(abs(center_dist)),
  ) %>% 
    pivot_longer(
    cols = -target_position,
    names_to = c("model", ".value"),
    names_sep = "_"
  ) %>% 
  mutate(
    model = factor(model, levels = c("data", "gazemodel", "linetracing", "motornoise", "random", "center"), labels = c("Data", "Gaze model", "Line-of-Sight", "LoS w. motor noise", "Random guessing", "Center bias")), 
  )

simulated_data <- simulated_data %>% 
  pivot_longer(
    cols = -c(subj_id, age, age_group, trial_nr, target_position, target_center_x),
    names_to = c("model", ".value"),
    names_sep = "_"
  ) %>%
  mutate(
    model = factor(model, levels = c("data", "gazemodel", "linetracing", "motornoise", "random", "center"), labels = c("Data", "Gaze model", "Line-of-Sight", "LoS w. motor noise", "Random guessing", "Center bias")), 
  )

saveRDS(simulated_data, file = "../saves/gazemodel_simulated_data.rds")
```

```{r simulated_data_plot}
sim_u <- simulated_mean %>% 
  ggplot(aes(x = target_position, y = dist, col = model, group = model)) +
  geom_point(alpha = 0.8, size = 1.5) +
  geom_line(alpha = 0.2) +
  scale_y_continuous(limits = c(0, 1920), breaks = seq(0, 1920, 320)) +
  labs(x = "Target bin", y = "Imprecision", col = "Source") + 
  scale_colour_viridis_d() +
  theme_minimal()

sim_cor <- simulated_wide %>% 
  group_by(age_group, target_position) %>%
  summarise(
    data = mean(abs(data_dist)),
    gazemodel = mean(abs(gazemodel_dist)),
    linetracing = mean(abs(linetracing_dist)),
    motornoise = mean(abs(motornoise_dist)),
    random = mean(abs(random_dist)),
    center = mean(abs(center_dist)),
  ) %>% 
  pivot_longer(cols = c(gazemodel, linetracing, motornoise, random, center), names_to = "model", values_to = "mean") %>% 
  mutate(
    model = factor(model, levels = c("gazemodel", "linetracing", "motornoise", "random", "center"), labels = c("Gaze model", "Line-of-Sight", "LoS w. motor noise", "Random guessing", "Center bias")), 
  ) %>% 
  ggplot(aes(x = mean, y = data)) +
  geom_point(aes(color = target_position, shape = as.factor(age_group)), alpha = 0.8, size = 0.8) +
  stat_cor(method = "pearson", label.x = 100, label.y = 960, aes(label = paste(..r.label..)), r.accuracy = 0.01, cor.coef.name = "r", size = 2.7, color = "black") +
  geom_abline(intercept = 0, slope = 1, linetype = 3) +
  labs(x = "Predicted imprecision", y = "Observed imprecision", color = "Target position", shape = "Age group") +
  scale_color_brewer(palette="BrBG") +
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 960, 320)) +
  scale_y_continuous(limits = c(0, 1000), breaks = seq(0, 960, 320)) +
  facet_wrap(~model) + 
  theme_minimal() +
  theme(axis.title = element_text(size = 6), 
        axis.text = element_text(size = 6), 
        strip.text = element_text(size = 7), 
        legend.title = element_text(size = 6),
        legend.text = element_text(size = 6), 
        legend.key.height = unit(0.3, "cm"),
        legend.key.width = unit(-1.5, "cm"),
        )
sim_cor

sim_click <- ggplot() +
  geom_point(data = simulated_data, aes(x = target_position, y = click, col = model), alpha = 0.2, size = 0.75) +
  geom_point(data = simulated_mean, aes(x = target_position, y = click, col = model), shape = 4, size = 2, stroke = 1.5) +
  geom_line(data = simulated_mean, aes(x = target_position, y = click, col = model, group = model)) +
  scale_y_continuous(limits = c(0, 1920), breaks = seq(0, 1920, 320)) +
  labs(x = "Target bin", y = "Click coordinate", col = "Source") + 
  scale_colour_viridis_d(guide = "none") +
  theme_minimal() + 
  facet_wrap(~ model, nrow = 1)

sim_arranged <- ggarrange(
  ggarrange(sim_u, sim_cor, ncol = 2, widths = c(1, 1), labels = c("A", "B")),
  
  sim_click,
  
  nrow = 2, 
  labels = c("", "C")
)

sim_arranged

ggsave("../figures/gazemodel_simulated_u.png", width = 9, height = 5, bg = "white")
```

```{r inward_clicks}
tango_kids %>% 
  mutate(
    dist = ifelse(target_center_x < 960, click_scaled_x - target_center_x, target_center_x - click_scaled_x),
  ) %>% 
  ggplot(aes(x = dist, y = target_position)) +
  geom_density_ridges() + 
  geom_point(stat = "summary", fun = "mean", shape = 4, size = 2.5, position = position_nudge(y = 0.1)) +
  geom_vline(xintercept = 0, lty = 2, alpha = .25) +
  scale_x_continuous(limits = c(-960, 1920), breaks = seq(-960, 1920, 320)) +
  labs(x = "Distance from target center (higher: inward)", y = "Target bin")

ggsave("../figures/gazemodel_inward_clicks.png", width = 8, height = 5, bg = "white", scale = 1.1)
```


