---
title: "Gaussian process"
author: "Julia Prein"
date: "2023-07-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse) # data handling etc.
library(tidybayes) # for stat_halfeye, add_predictive_draws
library(tidyboot) # for bootstrapped CIs
library(brms) # modeling
library(cmdstanr) # modeling
check_cmdstan_toolchain(fix = TRUE, quiet = TRUE)

options(scipen = 999)
theme_set(theme_classic())

# Seed for random number generation
set.seed(42)
```

```{r load_data}
lifespan_data <- readRDS("../data/tango-lifespan.rds")

mdata <- lifespan_data %>% 
  mutate(
    symmetric_position = abs(960 - target_center_x),
    symmetric_position = scale(symmetric_position) %>% round(2),
    trial_nr = trial_nr - min(trial_nr), 
    imprecision = click_dist_balloons + 0.005,
  ) %>% 
  select(subj_id, age, age_centered, symmetric_position, trial_nr, click_dist_balloons, imprecision)
```

```{r model_triallevel}
mgp_triallevel <- brm(imprecision ~ gp(age_centered, k=50, c=5/4, scale=TRUE) + symmetric_position + trial_nr + (1 + symmetric_position + trial_nr | subj_id),
                    data = mdata,
                    family = lognormal(),
                    warmup = 5000, 
                    iter   = 20000, 
                    chains = 4, 
                    cores  = 4, 
                    threads = threading(8), 
                    control = list(adapt_delta = 0.95), 
                    backend = "cmdstanr")

mgp_triallevel <- mgp_triallevel %>% add_criterion(c("loo","waic"))

write.csv(mgp_triallevel, "../saves/mgp_triallevel.csv", quote = F, row.names = F)
saveRDS(mgp_triallevel, "../saves/mgp_triallevel.rds")
```

```{r plot_triallevel}
mgp_triallevel

pp_check(mgp_triallevel)

conditional_effects(mgp_triallevel, ndraws = 200, spaghetti = TRUE) %>% 
  plot(points = T)
```


```{r model_aggregated}
mdata_aggregated <- mdata %>% 
  group_by(subj_id, age, age_centered) %>% 
  summarize(mean_imprecision = mean(click_dist_balloons, na.rm = TRUE))

mgp_aggregated <- brm(mean_imprecision ~ gp(age_centered, k=50, c=5/4, scale=TRUE),
                    data = mdata_aggregated,
                    family = lognormal(),
                    warmup = 5000, 
                    iter   = 20000, 
                    chains = 4, 
                    cores  = 4, 
                    threads = threading(8), 
                    control = list(adapt_delta = 0.95), 
                    backend = "cmdstanr")

mgp_aggregated <- mgp_aggregated %>% add_criterion(c("loo","waic"))

write.csv(mgp_aggregated, "../saves/mgp_aggregated.csv", quote = F, row.names = F)
saveRDS(mgp_aggregated, "../saves/mgp_aggregated.rds")
```

```{r plot_aggregated}
mgp_aggregated

pp_check(mgp_aggregated)

conditional_effects(mgp_aggregated, ndraws = 200, spaghetti = TRUE) %>% 
  plot(points = T)
```

```{r compare_models}
nd_triallevel <- mdata %>% 
  select(-c(imprecision, click_dist_balloons)) %>% 
  mutate(symmetric_position = 0, trial_nr = 0)

pred_triallevel <- fitted(mgp_triallevel, newdata = nd_triallevel, re_formula = NA) %>% as_tibble() %>% bind_cols(nd_triallevel) 

# same for aggregate

nd_aggregated <- mdata_aggregated %>% 
  select(-c(mean_imprecision))

pred_aggregated <- fitted(mgp_aggregated, newdata = nd_aggregated, re_formula = NA) %>% as_tibble() %>% bind_cols(nd_aggregated) 

pred_combined <-full_join(pred_aggregated %>% mutate(model = "subject level"), pred_triallevel %>% mutate(model = "trial level"))

# plot

ggplot() +
  
  geom_smooth(
    data = pred_combined, 
    aes(x = age, y = Estimate, ymin = Q2.5, ymax = Q97.5, group = model, col = model), 
    stat = "identity", size = 0.5, alpha = 0.15
  ) 
```

```{r aggregated_plot}
ggplot() +

  geom_jitter(
    data = mdata_aggregated, 
    aes(x = age, y = mean_imprecision), 
    col = "darkgrey", alpha = 0.75
  ) + 
  
  geom_smooth(
    data = pred_aggregated, 
    aes(x = age, y = Estimate, ymin = Q2.5, ymax = Q97.5), 
    stat = "identity", size = 1, alpha = 0.15, fill = "#006C66", col = "#006C66",
  ) + 
  
  scale_x_continuous(limits = c(0, 80), breaks = seq(0, 80, 5)) + 
  scale_y_continuous(limits = c(0, 4), breaks = seq(0, 4, 0.5)) + 
  
  labs(x = "Age in years", y = "Average imprecision in target width")
```
