---
title: "Change point analysis"
author: "Julia Prein"
date: "03/21/2023"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse) # data handling etc.
library(tidybayes) # for stat_halfeye, add_predictive_draws
library(tidyboot) # for bootstrapped CIs
library(brms) # modeling
library(cmdstanr) # modeling
library(Rbeast) # Bayesian change point analysis
check_cmdstan_toolchain(fix = TRUE, quiet = TRUE)

options(scipen = 999)
theme_set(theme_classic())

# Seed for random number generation
set.seed(42)
```

### Data preparation

```{r load_data}
lifespan_data <- readRDS("../data/tango-lifespan.rds")
```

```{r prepare_modeldata}
mdata <- lifespan_data %>% 
  group_by(subj_id, age, age_centered) %>% 
  summarize(mean_imprecision = mean(click_dist_balloons, na.rm = TRUE))

x <- mdata %>% arrange(age) %>% pull(age)
y <- mdata %>% arrange(age) %>% pull(mean_imprecision)
```

### BEASTs

```{r run_beasts, echo=T, message=FALSE, warning=FALSE, results=FALSE}
# this is the one we report in our paper: 
b0 <- beast.irreg(y = y, time = x, season = "none", 
            torder.minmax = c(0, 0), 
            tseg.min = 10, 
            mcmc.chains = 4, mcmc.burnin = 1000,  mcmc.samples = 10000, mcmc.seed = 42, 
            ci = TRUE)

b1 <- beast.irreg(y = y, time = x, season = "none", 
            torder.minmax = c(0, 0), 
            tcp.minmax = c(0, 5),
            tseg.min = 10, 
            mcmc.chains = 4, mcmc.burnin = 1000,  mcmc.samples = 10000, mcmc.seed = 42, 
            ci = TRUE)

b2 <- beast.irreg(y = y, time = x, season = "none", 
            mcmc.chains = 4, mcmc.burnin = 1000,  mcmc.samples = 10000, mcmc.seed = 42, 
            ci = TRUE)

b3 <- beast.irreg(y = y, time = x, season = "none", 
            torder.minmax = c(0, 0),
            mcmc.chains = 4, mcmc.burnin = 1000,  mcmc.samples = 10000, mcmc.seed = 42, 
            ci = TRUE)

b4 <- beast.irreg(y = y, time = x, season = "none", 
            torder.minmax = c(0, 0),
            tcp.minmax = c(0, 10), 
            mcmc.chains = 4, mcmc.burnin = 1000,  mcmc.samples = 10000, mcmc.seed = 42, 
            ci = TRUE)

b5 <- beast.irreg(y = y, time = x, season = "none", 
            torder.minmax = c(0, 0),
            tcp.minmax = c(0, 10), 
            tseg.min = 50, 
            mcmc.chains = 4, mcmc.burnin = 1000,  mcmc.samples = 10000, mcmc.seed = 42, 
            ci = TRUE)

b6 <- beast.irreg(y = y, time = x, season = "none", 
            torder.minmax = c(0, 0),
            tcp.minmax = c(0, 10), 
            tseg.min = 100, 
            mcmc.chains = 4, mcmc.burnin = 1000,  mcmc.samples = 10000, mcmc.seed = 42, 
            ci = TRUE)

b7 <- beast.irreg(y = y, time = x, season = "none", 
            torder.minmax = c(0, 0),
            tcp.minmax = c(0, 3), 
            mcmc.chains = 4, mcmc.burnin = 1000,  mcmc.samples = 10000, mcmc.seed = 42, 
            ci = TRUE)

b8 <- beast.irreg(y = y, time = x, season = "none", 
            torder.minmax = c(0, 0),
            tcp.minmax = c(0, 20), 
            mcmc.chains = 4, mcmc.burnin = 1000,  mcmc.samples = 10000, mcmc.seed = 42, 
            ci = TRUE)

b9 <- beast.irreg(y = y, time = x, season = "none", 
            torder.minmax = c(0, 0),
            tcp.minmax = c(0, 100), 
            mcmc.chains = 4, mcmc.burnin = 1000,  mcmc.samples = 10000, mcmc.seed = 42,
            ci = TRUE)


b10 <- beast.irreg(y = y, time = x, season = "none", 
            torder.minmax = c(0, 0),
            tcp.minmax = c(0, 100), 
            tseg.min = 100, 
            mcmc.chains = 4, mcmc.burnin = 1000,  mcmc.samples = 10000, mcmc.seed = 42, 
            ci = TRUE)

b11 <- beast.irreg(y = y, time = x, season = "none", 
            torder.minmax = c(0, 0),
            tcp.minmax = c(0, 72), # as max nr, since 719 datapoints, 10 tseg.min
            tseg.min = 10, 
            mcmc.chains = 4, mcmc.burnin = 1000,  mcmc.samples = 10000, mcmc.seed = 42, 
            ci = TRUE)
```

```{r fct_printbeasts}
showBeast <- function(beast) {
  
  print(beast)
  plot(beast)
  print("...continuing to next beast")
}
```

```{r actually_printbeasts}
beasts <- list(b0, b1, b2, b3, b4, b5, b6, b7, b8, b9, b10, b11)

counter = 0

for (i in beasts) {
  print("")
  print("This is the BEAST...")
  print(counter)
  print("")
  
  showBeast(i)
  counter = counter + 1 
}
```

### To judge nr of data points between change points 

```{r}
mdata <- mdata %>% 
  ungroup() %>% 
  arrange(age) %>% 
  mutate(
    age_diff = lead(age) - age, 
    age_years = floor(age), 
    three_year_bins = case_match(age_years %% 3, 
                                 0 ~ age_years,
                                 1 ~ age_years-1,
                                 2 ~ age_years-2),
  ) %>% 
  select(-age_years)


mean_age_diff <- mean(mdata$age_diff, na.rm = T) %>% round(2)

mean_n_per_3y <- mdata %>% 
  group_by(three_year_bins) %>% 
  summarize(n_per_bin = n()) %>% 
  summarize(mean_n_per_3y = mean(n_per_bin) %>% round(2)) %>% 
  pull(mean_n_per_3y)

mean_age_diff
# [1] 0.11 corresponds to mean age difference between consecutive points on the x-axis

mean_n_per_3y
# [1] 27.65 data points correspond to 3 years of development
```

```{r}
b11

plot(b11)

str(b11)

# Y: a vector of length N; the estimated trend component.It is the Bayesian model averaging of all the individual sampled trend.
b11$trend$Y

plot(b11, vars = c('t', 'y'))

plot(b11$time, b11$trend$Y, type = 'l') # #directly plot output: the fitted trend

plot(b11$time, b11$trend$cpOccPr) # #directly plot output: trend chgpt occurrence prob
```

```{r}
est <- tibble(age = x, data = y, model = b11$trend$Y)
cps <- b11$trend$cp[1:b11$trend$ncp_median]

ggplot(data = est, aes(data, model)) + 
  geom_point() +
  geom_smooth(method = "lm") + 
  stat_cor() +
  scale_x_continuous(limits = c(0, 3), breaks = seq(0, 3, 0.5)) +
  scale_y_continuous(limits = c(0, 3), breaks = seq(0, 3, 0.5))

n_distinct(est$model)

est %>% 
  pivot_longer(cols = c(data, model), names_to = "source") %>% 
  ggplot(aes(x = age, y = value, color = as.factor(source))) + 
  geom_point(alpha = 0.5) +
  geom_vline(xintercept = cps, linetype = "dashed", alpha = 0.9, size = 0.75) +
  scale_color_manual(values = c("darkblue", "orange")) +
  scale_x_continuous(limits = c(3, 80), breaks = seq(0, 80, 5)) +
  scale_y_continuous(limits = c(0, 2.5), breaks = seq(0, 2.5, 0.5)) + 
  labs(x = "Age", y = "Mean imprecision", color = "Source")

est %>% 
  pivot_longer(cols = c(data, model), names_to = "source") %>% 
  filter(source == "model", age >= 20) %>%
  ggplot(aes(x = age, y = value)) + 
  geom_point() +
  geom_vline(xintercept = cps, linetype = "dashed", alpha = 0.9, size = 0.75) +
  scale_x_continuous(limits = c(20, 80), breaks = seq(0, 80, 5)) +
  scale_y_continuous(limits = c(0.5, 1), breaks = seq(0.5, 1, 0.5)) +
  labs(x = "Age", y = "Mean imprecision")
```

